# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: GeoffreyChen.Paperlib
PackageVersion: 2.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ReleaseDate: 2022-09-19
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-2.0.0/Paperlib_2.0.0.exe
  InstallerSha256: 245CF212E27F013C6A8EC68A99B4A498D7CA04DBA343838899534DA990F48AC4
  InstallerSwitches:
    Custom: /currentuser
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-2.0.0/Paperlib_2.0.0.exe
  InstallerSha256: 245CF212E27F013C6A8EC68A99B4A498D7CA04DBA343838899534DA990F48AC4
  InstallerSwitches:
    Custom: /allusers
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.2.0
