# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 $debug=QUSU.7-2-7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: GeoffreyChen.Paperlib
PackageVersion: 2.1.0
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ReleaseDate: 2022-11-05
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-2.1.0/Paperlib_2.1.0.exe
  InstallerSha256: F874613254AB4CA56DB266F3033BE74BE79682164A3C07BE9C34DE36D6EC8DF0
  InstallerSwitches:
    Custom: /currentuser
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-2.1.0/Paperlib_2.1.0.exe
  InstallerSha256: F874613254AB4CA56DB266F3033BE74BE79682164A3C07BE9C34DE36D6EC8DF0
  InstallerSwitches:
    Custom: /allusers
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.2.0
