# Created with YamlCreate.ps1 v2.2.1 using InputObject 🤖 $debug=QUSU.CRLF.7-2-10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: GeoffreyChen.Paperlib
PackageVersion: 2.2.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ReleaseDate: 2023-03-17
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Future-Scholars/paperlib/releases/download/release-electron-2.2.0/Paperlib_2.2.0.exe
  InstallerSha256: C0E3FCFC356E57402331A759EFAB41A2553BCB98DCC6555EF329BF3724DD1478
  InstallerSwitches:
    Custom: /currentuser
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Future-Scholars/paperlib/releases/download/release-electron-2.2.0/Paperlib_2.2.0.exe
  InstallerSha256: C0E3FCFC356E57402331A759EFAB41A2553BCB98DCC6555EF329BF3724DD1478
  InstallerSwitches:
    Custom: /allusers
  ProductCode: 1d30f4d8-0e3b-5fc9-bdad-f2c67c2b5c34
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.2.0
